# Implementation of Inertial NETS on the 40-mode GMM from FAB

# Run Details
run_name: nets_learned_inertial_unnamed
run_group: nets
wandb: false
wandb_project: ${oc.env:WANDB_PROJECT, null}
checkpoint: null

# Objective Details
x_dim: 2
density_path: learnable_linear
learnable_hiddens: [256, 256, 256]
target: fab_gmm
cov_scale: 0.25
source_std: 5.0

# Training details
num_devices: 1
max_epochs: 800
lr: 0.002
lr_burn_in_epochs: 150
step_size: 5
gamma: 0.97
checkpoint_burn_in_epochs: 150

# Batching details
use_persistent_sample_buffer: true
persistent_sample_buffer_trajectories: 2000
train_trajectories: 250
train_steps_per_epoch: 100
val_trajectories: 1000
val_steps_per_epoch: 2
val_freq: 5

# PINN-specific training details
annealing_scheduler: manual
T_schedule: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
epochs_per_T: [10, 10, 10, 10, 20, 20, 20, 30, 30, 30]
avg_dt: 0.002
record_every: 20
divergence_mode: autograd

# Control-specific details
control: mlp
control_hiddens: [256, 256, 256]

# Free-energy specific details
free_energy: mlp
free_energy_hiddens: [256, 256, 256]

# Time-encoding details
use_fourier: true
x_fourier_dim: 100
x_fourier_sigma: 0.1
t_fourier_dim: 20
t_fourier_sigma: 5

# Proposal details
proposal: underdamped_langevin
scale: 50.0
damping: 2.0
mass: 1.0
hamiltonian_type: standard
use_jarzynski: true

# TODO: metrics used
verbose: false
memory_profile: false

