run_name: nets_linear_random_gmm
run_group: nets_random
wandb: false
wandb_project: null

x_dim: 2
density_path: linear
target: random_gmm
target_nmodes: 5
target_scale: 6.0
target_std: 0.6
target_seed: 7
cov_scale: 1.0
source_std: 2.0

device: cpu
seed: 7
max_epochs: 50
lr: 0.001
lr_burn_in_epochs: 0
step_size: 10
gamma: 0.97
checkpoint_burn_in_epochs: 0
save_top_k: 1
plot_every_n_epochs: 10
plot_num_trajectories: 24
plot_min_points: 2000

use_persistent_sample_buffer: false
persistent_sample_buffer_trajectories: 8
train_trajectories: 8
train_steps_per_epoch: 1
val_trajectories: 8
val_freq: 1

annealing_scheduler: manual
T_schedule: [1.0]
epochs_per_T: [1]
avg_dt: 0.25
record_every: 2
divergence_mode: autograd

control_hiddens: [16, 16]
free_energy_hiddens: [16, 16]

use_fourier: false
x_fourier_dim: 8
x_fourier_sigma: 0.1
t_fourier_dim: 8
t_fourier_sigma: 1.0

damping: 1.0
use_jarzynski: true

verbose: false
memory_profile: false

hydra:
  run:
    dir: .
  output_subdir: null
